// The Production Acceptance Matrix for the Travessia voyage (issue #45, replacing
// the Instituto Maré Aberta matrix of #19). `docs/acceptance-matrix.md` is
// generated from this file with `bun run acceptance:matrix`; the Release Dossier
// evaluates every row against candidate-bound evidence.

export type RowGroup = "A" | "B" | "C" | "D" | "E" | "F" | "R";

export type CapturePoint = { id: string; label: string };

export type AcceptanceRow = {
  id: string;
  group: RowGroup;
  title: string;
  // The observable criterion and the target presentation, device, or input state.
  criterion: string;
  method: string;
  evidence: string;
  threshold: string;
  // Only cosmetic rows, whose differences cannot affect meaning, legibility,
  // interaction, accessibility, or performance, may carry an approved waiver.
  waivable: boolean;
  // Automated evidence: check ids recorded by `bun run evidence` (ci/…) and the
  // Playwright evidence reporter (e2e/<project>/<spec>).
  checks: string[];
  // Manual evidence: one record per capture point.
  captures: CapturePoint[];
  checklist: string[];
  // Work the row depends on that has not landed; its evidence cannot exist yet.
  awaiting?: string;
};

export const rowGroups: Record<RowGroup, string> = {
  A: "Automated checks",
  B: "Browser walkthroughs and visual review",
  C: "Accessibility evaluation",
  D: "Copy, Evidence Boundary, and provenance review",
  E: "Physical-device release gate",
  F: "First-time Visitor study",
  R: "Release sign-off",
};

// Evidence older than this, recorded before the candidate commit, or dated in
// the future is stale. The skew absorbs clock differences between machines.
export const evidencePolicy = { maxAgeDays: 30, clockSkewMinutes: 5 } as const;

export const engines = ["chromium", "firefox", "webkit"] as const;
const inEveryEngine = (spec: string) => engines.map((engine) => `e2e/${engine}/${spec}`);

// The mandatory physical suite approved in #13 and carried into #46.
export const deviceSuite: CapturePoint[] = [
  { id: "iphone-safari", label: "Current Safari on a base recent iPhone" },
  { id: "android-a-chrome", label: "Current Chrome on mid-range Android phone A" },
  { id: "android-b-chrome", label: "Current Chrome on mid-range Android phone B" },
  { id: "windows-chrome", label: "Current Chrome on an integrated-graphics Windows laptop" },
  { id: "windows-firefox", label: "Current Firefox on the same Windows laptop" },
  { id: "macbook-safari", label: "Current Safari on a base Apple-silicon MacBook Air" },
];

const viewports: CapturePoint[] = [
  { id: "desktop", label: "Desktop browser at 1440×900" },
  { id: "phone-portrait", label: "Phone layout at 390×844" },
  { id: "phone-landscape", label: "Phone layout at 844×390" },
];

const desktopAndPhone: CapturePoint[] = [
  { id: "desktop", label: "Desktop (Balanced)" },
  { id: "phone", label: "Phone (Low)" },
];

export const acceptanceMatrix: AcceptanceRow[] = [
  {
    id: "A1",
    group: "A",
    title: "Clean CI",
    criterion: "The candidate installs, checks, and builds from a clean checkout, and no step leaves an unexpected generated diff.",
    method: "GitHub Actions on a clean runner runs `bun install --frozen-lockfile`, `bun run typecheck`, `bun run lint`, `bun test`, and `bun run build`, then compares the working tree with the candidate commit, each step wrapped by `bun run evidence`.",
    evidence: "Candidate-bound evidence records with the retained log of every command.",
    threshold: "Every command exits zero on a tree that matches the candidate, and the final tree, including untracked files, is unchanged.",
    waivable: false,
    checks: ["ci/install", "ci/typecheck", "ci/lint", "ci/unit-tests", "ci/build", "ci/generated-diff"],
    captures: [],
    checklist: [],
  },
  {
    id: "A2",
    group: "A",
    title: "Voyage State persistence",
    criterion: "Voyage State records the current Stop, Visited Stops, Voyage Complete, and the Ship's place on the Charted Route; both presentations share it; it survives reload and back/forward in the same tab and clears on “Recomeçar viagem”.",
    method: "Unit tests of transitions and tab-scoped persistence (`tests/voyage-state.test.ts`); browser journeys for reload, history, completion, restart, and reading mode across reload.",
    evidence: "Unit-test and per-engine browser evidence records.",
    threshold: "Every Stop is reachable in any order; the Arrival completes the Voyage whatever has been visited; only opening a Stop Account visits a Stop; unreadable or invalid storage starts a new Voyage safely; every journey passes in every engine.",
    waivable: false,
    checks: ["ci/unit-tests", ...inEveryEngine("charted-route"), ...inEveryEngine("presentation-switching")],
    captures: [],
    checklist: [],
  },
  {
    id: "A3",
    group: "A",
    title: "Charted Route input and settling",
    criterion: "Wheel and trackpad, touch swipes, held and tapped arrow keys, PageUp/PageDown, and “Capítulos” move the Ship along the one fixed route. It calls at every Stop, settles into a Stop within reach when input stops, rests in open water otherwise, and never leaves the route.",
    method: "Unit tests of the route, motion, camera, and Landmark clearance; browser journeys for wheel, touch, held and tapped keys, docking, open water, and chapter jumps.",
    evidence: "Unit-test and per-engine browser evidence records.",
    threshold: "One gesture sails at most one passage; a step moves exactly one Stop; the Ship never turns back to a Stop left behind; route input is ignored while a Sheet is open or the page is hidden; every journey passes in every engine.",
    waivable: false,
    checks: ["ci/unit-tests", ...inEveryEngine("charted-route"), ...inEveryEngine("sheets")],
    captures: [],
    checklist: [],
  },
  {
    id: "A4",
    group: "A",
    title: "Minimal chrome and Stop Cards",
    criterion: "Only the Travessia logo, the sound toggle, “Capítulos”, and “Modo leitura” persist over the ocean; loading is a logo fade. Stop Cards fade in when the Ship settles and out when it sails, sit clear of the Ship, its Landmark, and the chrome, and the Stop 00 “Role para navegar” cue never returns in the tab.",
    method: "Browser journeys over the chrome, card content and fading, the scroll cue across reload, announcements, and card placement.",
    evidence: "Per-engine browser evidence records.",
    threshold: "No legacy control, quality selector, or preparation button; each arrival is announced once; cards stay clear at 1440×900, 844×390, 568×320, 390×844, and 320×568; every journey passes in every engine.",
    waivable: false,
    checks: [...inEveryEngine("stop-cards"), ...inEveryEngine("ocean-entry")],
    captures: [],
    checklist: [],
  },
  {
    id: "A5",
    group: "A",
    title: "Stop Account and Capítulos Sheets, and the Arrival",
    criterion: "“Saiba mais” opens the Stop Account as a white Sheet (right, 520px, from 48rem; bottom, 90% height, below) and records a Visited Stop. “Capítulos” lists Stops 00–04 with visited ticks and the current Stop, jumps without visiting, and offers “Modo leitura” and “Recomeçar viagem”. The Arrival's closing card opens the itinerary and restarts.",
    method: "Browser journeys over Sheet placement, content order, closing, focus, visited ticks, chapter jumps, restart, and the closing card.",
    evidence: "Per-engine browser evidence records.",
    threshold: "X, Escape, and the dimmed ocean close a Sheet; focus is trapped and returned to its opener; wheel, touch, and keys never move the Ship while a Sheet is open; no personal-data field exists; every journey passes in every engine.",
    waivable: false,
    checks: [...inEveryEngine("sheets"), ...inEveryEngine("charted-route")],
    captures: [],
    checklist: [],
  },
  {
    id: "A6",
    group: "A",
    title: "Reduced-motion cuts",
    criterion: "A reduced-motion preference keeps the 3D voyage, cuts between Stops instead of sailing or resting in open water, calms waves and surf, disables pitch and roll, clears the wake on each cut, and moves the editorial page without animated scrolling.",
    method: "Unit tests of reduced-motion cuts, wake clearing, and calmer buoyancy; reduced-motion browser journeys for travel, chapter cuts, entry, focus movement, and the shared wave uniforms.",
    evidence: "Unit-test and browser evidence records.",
    threshold: "No sailing, open-water rest, pitch, roll, or smooth scrolling under reduced motion; the preference never opens reading mode; every journey passes in every engine where it runs.",
    waivable: false,
    checks: ["ci/unit-tests", ...inEveryEngine("charted-route"), ...inEveryEngine("sheets"), ...inEveryEngine("accessibility"), "e2e/chromium/ocean-daylight"],
    captures: [],
    checklist: [],
  },
  {
    id: "A7",
    group: "A",
    title: "Editorial parity and presentation switching",
    criterion: "The Accessible Editorial Presentation carries the brand, the fictional-project disclosure, every Stop Account in route order, the itinerary, and the same Voyage State. It is complete without JavaScript, and switching in either direction is atomic.",
    method: "Browser journeys switching at Stop 00, at each Stop, around every Stop Account, and at the Arrival; a no-JavaScript read of every Stop Account.",
    evidence: "Per-engine browser evidence records.",
    threshold: "Switching never visits, advances, or completes; focus lands on the current Stop's heading (or the h1 at Stop 00) and on the ocean surface on return; the disclosure appears once per presentation; every Stop Account reads without JavaScript.",
    waivable: false,
    checks: [...inEveryEngine("presentation-switching"), ...inEveryEngine("ocean-entry"), ...inEveryEngine("accessibility")],
    captures: [],
    checklist: [],
  },
  {
    id: "A8",
    group: "A",
    title: "WebGL failure fallback and resilience",
    criterion: "Missing WebGL, a refused context, essential asset or shader failure, context loss, and sustained unusable quality open the Accessible Editorial Presentation at the matching place with one explanation line. One restoration is attempted, and optional failures degrade without blocking.",
    method: "Browser journeys simulating unsupported and refused WebGL, asset and shader failures, real context loss and restoration, recovery timeouts, lifecycle pauses, and slow Low frames.",
    evidence: "Per-engine browser evidence records.",
    threshold: "The explanation is announced once; “Voltar ao oceano” appears only while 3D remains available; a second loss or failed recovery locks 3D for the visit; hidden pages pause without a time-step jump; fonts and vessel detail never gate readiness.",
    waivable: false,
    checks: [...inEveryEngine("ocean-entry"), "e2e/chromium/ocean-resilience"],
    captures: [],
    checklist: [],
  },
  {
    id: "A9",
    group: "A",
    title: "Automated accessibility",
    criterion: "Representative states of both presentations have no machine-detectable WCAG 2.2 A/AA violation; keyboard focus is visible, ordered, and never trapped; layouts reflow at the target viewports, 200% and 400% zoom, and increased text spacing.",
    method: "axe-core scans of loading, the opening, Stop Cards, Sheets, the Arrival, reading mode, reduced motion, and failure states; keyboard walks; layout checks.",
    evidence: "Per-engine browser evidence records with the `axe-<state>.json` incomplete-rule reports.",
    threshold: "Zero axe violations; every incomplete rule is retained per state for manual classification (C6) and never counted as a pass; every journey passes in every engine.",
    waivable: false,
    checks: [...inEveryEngine("accessibility"), ...inEveryEngine("keyboard"), ...inEveryEngine("layout")],
    captures: [],
    checklist: [],
  },
  {
    id: "A10",
    group: "A",
    title: "Asset provenance and reproducibility",
    criterion: "Every served file, font, model, image, and recorded source has an approved source, rights, proof, transformation history, and matching SHA-256; the Ship and Landmark masters regenerate byte-identically; production requests stay on the application origin and match the ledger.",
    method: "`bun run assets:audit`; regeneration of the Ship and Landmarks followed by a tree comparison; the production gate hashes every deployed request.",
    evidence: "CI evidence records and the production budget report.",
    threshold: "The audit passes, regeneration leaves no diff, and no request is unregistered, failed, or hosted by a third party.",
    waivable: false,
    checks: ["ci/asset-audit", "ci/reproducible-assets", "ci/unit-tests", "e2e/production/production-assets"],
    captures: [],
    checklist: [],
  },
  {
    id: "A11",
    group: "A",
    title: "Transfer, asset, and scene budgets",
    criterion: "Production transfer and actual renderer counts for the Ship, the Landmarks, and the water stay within the approved budgets at Balanced and Low.",
    method: "The production gate measures gzip-conservative transfer and renderer draws, triangles, and retained targets; unit tests inspect the shipped Ship and Landmark GLBs; the daylight suite compiles every tier with a Landmark visible.",
    evidence: "The production budget report, local diagnostics, and evidence records.",
    threshold: "Route JS ≤200 KiB; lazy 3D JS ≤350 KiB; minimum sailable ≤1.5 MiB; complete first visit ≤5 MiB; minimum-sailable authored visuals ≤500 KiB; all authored visuals ≤750 KiB; fonts ≤160 KiB; Balanced <100 draws and <150,000 triangles with one ocean draw and ≤1 retained target; Low retains no target; Ship ≤12,000 triangles and 250 KiB (Balanced), ≤4,000 and 120 KiB (Low); each Landmark ≤4,400 triangles and 76 KiB (Balanced) or ≤1,300 and 28 KiB (Low), two draws, no textures. A missing measurement fails.",
    waivable: false,
    checks: ["ci/unit-tests", "e2e/production/production-assets", "e2e/chromium/ocean-daylight"],
    captures: [],
    checklist: [],
  },
  {
    id: "A12",
    group: "A",
    title: "Lab Core Web Vitals",
    criterion: "Cold-cache loads of the Visitor's default entry, followed by representative interactions (opening and closing “Capítulos”, a route key on desktop, and “Modo leitura”), meet the approved Core Web Vitals thresholds in the lab.",
    method: "`bun run test:vitals` against the production build: at least five cold-cache runs per profile, each in a fresh browser context on a hardware-accelerated renderer; mobile and desktop p75 (nearest rank) calculated separately.",
    evidence: "The lab report with every run, both profiles, the renderer, host, and tool versions, and the p75 calculation, labelled as lab evidence.",
    threshold: "Mobile and desktop p75 each meet LCP ≤2.5 s, INP ≤200 ms, and CLS ≤0.1. These are lab results and are never reported as field data; runs on a software renderer are withheld and stay Unvalidated.",
    waivable: false,
    checks: ["e2e/lab-vitals/lab-vitals"],
    captures: [],
    checklist: [],
  },
  {
    id: "A13",
    group: "A",
    title: "Opt-in ambient sound",
    criterion: "The ambient ocean and engine loop is off by default, starts only from the sound toggle, reflects its state through `aria-pressed`, and falls silent when the page is hidden or leaves the ocean scene.",
    method: "A browser journey over the default state, toggling, page visibility, and reading mode.",
    evidence: "Per-engine browser evidence records.",
    threshold: "Nothing sounds before the toggle is pressed; toggling off stops the loop; a hidden page or reading mode silences it; every journey passes in every engine.",
    waivable: false,
    checks: inEveryEngine("sound"),
    captures: [],
    checklist: [],
    awaiting: "#42 — the ambient loop and its browser journey are not built yet.",
  },
  {
    id: "B1",
    group: "B",
    title: "Voyage walkthrough at capture points",
    criterion: "A reviewer completes the Voyage from Stop 00 to the Arrival and back through every surface at each capture viewport.",
    method: "Manual walkthrough of the candidate's production build in current desktop Chrome, with DevTools device emulation for the phone layouts.",
    evidence: "One screenshot per capture point listed in the checklist, and the completed checklist.",
    threshold: "Every checklist item holds at every viewport, with no clipped, overlapping, or unreachable element.",
    waivable: false,
    checks: [],
    captures: viewports,
    checklist: [
      "First load shows only the Travessia logo fade, then the ocean. Capture: Stop 00.",
      "Stop 00 shows Travessia, “O Brasil visto do mar.”, and “Role para navegar”; the cue disappears on the first scroll and stays gone after reload.",
      "Scrolling or a trackpad sails the Ship; stopping near a Stop settles there and shows its Stop Card; stopping far from one rests in open water with no card.",
      "Arrow keys and PageUp/PageDown step exactly one Stop.",
      "Each Stop Card shows “Parada 0N”, its context line, title, one sentence, and “Saiba mais”. Capture: each Stop Card 01–04.",
      "“Saiba mais” opens the Stop Account (right Sheet on desktop, bottom Sheet on phones) as one continuous scroll, closing with X, Escape, and the dimmed ocean. Capture: an open Stop Account.",
      "“Capítulos” ticks visited Stops, marks the current one, and jumps without visiting. Capture: Capítulos open.",
      "“Modo leitura” and “Voltar ao oceano” keep the place and Visited Stops; so does a reload. Capture: the editorial page at its top and at one Stop.",
      "The Arrival's closing card shows “Próxima partida · setembro de 2027”; “Ver roteiro completo” opens the itinerary; “Recomeçar viagem” returns to Stop 00. Capture: the closing card and the itinerary.",
      "No form, booking action, or personal-data field appears anywhere.",
    ],
  },
  {
    id: "B2",
    group: "B",
    title: "Visual direction",
    criterion: "The candidate reads as the approved Travessia direction: a navy, near-black ocean ground, white type, one coral accent, Manrope headlines and Geist Mono labels, a near top-down camera (75–85°), almost no chrome, and white editorial Sheets, comparable in polish to the OceanX reference.",
    method: "Human comparison of the B1 capture points and the production gate's aerial screenshots with the direction in #33. Procedural water is compared by eye, not pixel by pixel.",
    evidence: "Annotated screenshots and a signed visual review.",
    threshold: "The direction is recognisable at every capture point. A cosmetic difference with no effect on meaning, legibility, interaction, accessibility, or performance may carry an owner-approved waiver.",
    waivable: true,
    checks: [],
    captures: desktopAndPhone,
    checklist: [
      "Ocean ground is navy to near-black; type is white; coral appears only as the single accent and never carries meaning alone.",
      "Headlines use Manrope and labels Geist Mono; nothing falls back to a system font once fonts load.",
      "The camera looks almost straight down, north up, with the Ship left of centre on landscape and above centre on portrait.",
      "Only the logo, sound toggle, “Capítulos”, “Modo leitura”, and the current Stop Card stand over the ocean.",
      "Sheets and the editorial page share the white editorial language: ink type, grey hairlines, mono labels, coral dots.",
    ],
  },
  {
    id: "B3",
    group: "B",
    title: "Landmarks, Ship, and water",
    criterion: "From the route camera each Stop is recognisable by its island, with a surf line meeting the water and no floating label or beacon; the Ship reads as a detailed expedition vessel at Balanced and Low; the water keeps its navy daylight look, wake, and reduced-motion calm.",
    method: "Human review at every Stop in both tiers, with and without reduced motion.",
    evidence: "One capture per Stop per tier and a signed review.",
    threshold: "Every Stop is distinguishable without text; no island floats, leaves a seam at the water, or carries a label or light; the Ship's silhouette and detail hold at both tiers; the wake follows the Ship and clears on a cut.",
    waivable: false,
    checks: [],
    captures: desktopAndPhone,
    checklist: [
      "Fernando de Noronha shows its volcanic peak; Boipeba a low, forested island; Abrolhos a low archipelago; Ilha Grande a mountainous island.",
      "Each island's surf line meets the moving water with no gap, flicker, or seam.",
      "No Stop carries a floating label, beacon, or light marker.",
      "The Maré Mansa reads as a detailed expedition vessel at Balanced (desktop) and Low (phone).",
      "The water keeps its navy daylight colour, whitecaps (Balanced), glints, and wake; under reduced motion the waves calm and the hull stays level.",
    ],
  },
  {
    id: "B4",
    group: "B",
    title: "Ambient sound listening check",
    criterion: "The ambient loop is subtle, loops without an audible seam, never plays before the Visitor opts in, and stays off after a reload unless chosen again.",
    method: "Manual listening on desktop speakers and phone headphones.",
    evidence: "Tester notes per capture point.",
    threshold: "No sound before opt-in; no audible seam, clipping, or sudden volume change; the toggle's spoken state matches what is heard.",
    waivable: false,
    checks: [],
    captures: desktopAndPhone,
    checklist: [
      "The page is silent on load and after a reload until “Som ambiente” is pressed.",
      "The loop is quiet enough to sit under reading, loops without a seam, and never clips.",
      "Pressing the toggle again, hiding the tab, or opening “Modo leitura” silences it.",
    ],
    awaiting: "#42 — the ambient loop is not built yet.",
  },
  {
    id: "C1",
    group: "C",
    title: "WCAG 2.2 AA conformance",
    criterion: "The complete Live Experience, in both presentations and every state, conforms to WCAG 2.2 Level AA.",
    method: "A WCAG-EM-style evaluation scoped to loading, Stops 00–04, Stop Cards, both Sheets, the Arrival and itinerary, reading mode, failure notices, and reduced motion, combining automated findings with knowledgeable manual review.",
    evidence: "A success-criterion report naming states, technologies, tools, and the evaluator.",
    threshold: "Every applicable Level A and AA success criterion passes across the whole process; no automated score substitutes for conformance.",
    waivable: false,
    checks: [],
    captures: [{ id: "evaluation", label: "WCAG-EM-style evaluation report" }],
    checklist: [
      "Scope both presentations and every state listed in the method; name the browsers and assistive technologies relied upon.",
      "Evaluate every applicable A and AA success criterion; record each result with the states it covers.",
      "Link each failure to a fix and retest on this candidate, or record the row as Fail.",
    ],
  },
  {
    id: "C2",
    group: "C",
    title: "Keyboard-only Voyage",
    criterion: "Keyboard-only use reaches and operates every meaningful action in both presentations without traps or lost focus.",
    method: "Complete the 3D and editorial Voyages with Tab, Shift+Tab, Enter, Space, arrow keys, PageUp/PageDown, and Escape only.",
    evidence: "A keystroke walkthrough and focus-order captures.",
    threshold: "Every action is reachable with a visible, unobscured focus indicator; order follows meaning; focus is never trapped or lost; Escape closes only the top Sheet and never changes presentation.",
    waivable: false,
    checks: [],
    captures: [
      { id: "3d", label: "3D presentation" },
      { id: "editorial", label: "Accessible Editorial Presentation" },
    ],
    checklist: [
      "Focus order over the ocean: skip link, sound toggle, “Capítulos”, the Stop Card, “Modo leitura”.",
      "Arrow keys and PageUp/PageDown travel between Stops; “Saiba mais” opens the Stop Account; Escape closes it and focus returns to “Saiba mais”.",
      "“Capítulos” jumps, “Recomeçar viagem”, and the closing card's actions all work from the keyboard.",
      "On the editorial page every route entry, “Voltar à rota”, “Recomeçar viagem”, and “Voltar ao início” is reachable with a visible ring, and the walk leaves the page.",
    ],
  },
  {
    id: "C3",
    group: "C",
    title: "Screen readers",
    criterion: "Named screen-reader and browser pairs expose correct structure, names, states, and announcements through the complete Voyage.",
    method: "Complete the critical path with each pair on a real device: arrive at every Stop, open a Stop Account, use “Capítulos”, switch presentations, reach the Arrival, and restart.",
    evidence: "Versioned walkthrough notes or recordings per pair.",
    threshold: "Headings, landmarks, names, roles, values, visited and current states, progress, arrivals, Sheet titles, and failure lines are understandable; polite announcements neither steal focus nor repeat excessively.",
    waivable: false,
    checks: [],
    captures: [
      { id: "nvda-firefox", label: "NVDA with Firefox on Windows" },
      { id: "voiceover-safari-macos", label: "VoiceOver with Safari on macOS" },
      { id: "voiceover-safari-iphone", label: "VoiceOver with Safari on iPhone" },
      { id: "talkback-chrome-android", label: "TalkBack with Chrome on Android" },
    ],
    checklist: [
      "The page title, the h1, and the landmarks are announced; the Travessia wordmark has a name and the mark is decorative.",
      "Each arrival at a Stop is announced once; the Stop Card is named by its title.",
      "Sheets announce their title, keep reading inside the Sheet, and return to the opener on close.",
      "Visited and current Stops are spoken in words (“Visitada”, “Parada atual”); progress reads as “N de 4 paradas visitadas”.",
      "The sound toggle speaks its pressed state; images speak their Portuguese alt text; a failure line is announced once.",
    ],
  },
  {
    id: "C4",
    group: "C",
    title: "Zoom, reflow, contrast, and text spacing",
    criterion: "Text, controls, Sheets, and the editorial page stay legible and operable under magnification, reflow, increased text spacing, forced colours, and larger default fonts.",
    method: "Manual checks at 200% and 400% zoom, WCAG 1.4.12 text spacing, Windows contrast themes, a larger browser font size, and a notched phone's safe areas.",
    evidence: "Captures at each setting and computed contrast results.",
    threshold: "WCAG 2.2 AA contrast, reflow, and text-spacing criteria pass; focus stays visible; no essential text or action is clipped, overlapped, or hidden.",
    waivable: false,
    checks: [],
    captures: [
      { id: "desktop", label: "Desktop browser" },
      { id: "phone", label: "Physical phone" },
    ],
    checklist: [
      "At 200% and 400% zoom the Stop Card still reaches “Saiba mais”, Sheets scroll as one column, and the editorial page reflows to one column.",
      "With text spacing increased, nothing clips or overlaps.",
      "In a Windows contrast theme every control, focus ring, and state remains visible.",
      "Chrome controls clear the notch and home indicator on a phone in both orientations.",
    ],
  },
  {
    id: "C5",
    group: "C",
    title: "Reduced motion on real systems",
    criterion: "With the operating system's reduce-motion setting on, the voyage stays in 3D and remains comfortable: cuts between Stops, calm water, a level Ship, and no animated scrolling.",
    method: "Enable reduce motion on macOS or Windows and on a phone, then complete the Voyage.",
    evidence: "Tester notes and a short recording per capture point.",
    threshold: "No sailing animation, pitch, roll, sliding card, or smooth scroll; reading mode does not open because of the setting; the tester reports no discomfort.",
    waivable: false,
    checks: [],
    captures: desktopAndPhone,
    checklist: [
      "The ocean opens in 3D, not reading mode.",
      "Scrolling, keys, and “Capítulos” cut from Stop to Stop; the Ship never rests in open water.",
      "Waves and surf move slowly; the Ship stays level; Stop Cards appear without sliding.",
      "Route jumps on the editorial page move without smooth scrolling.",
    ],
  },
  {
    id: "C6",
    group: "C",
    title: "Accessibility reconciliation",
    criterion: "Human review reconciles the automated scans with the keyboard, screen-reader, zoom, and motion walkthroughs and documents every limitation.",
    method: "The technical and accessibility reviewer classifies every `axe-<state>.json` incomplete result from A9 and every finding from C1–C5.",
    evidence: "The signed accessibility section of the Release Dossier.",
    threshold: "No unresolved applicable finding. If no evaluation with disabled participants took place, that limitation is recorded as an unvalidated risk and the experience is not described as user-validated by people with disabilities.",
    waivable: false,
    checks: [],
    captures: [{ id: "reconciliation", label: "Accessibility reconciliation" }],
    checklist: [
      "Classify every incomplete axe rule in each `axe-<state>.json` from the candidate's A9 evidence.",
      "Confirm every C1–C5 finding is fixed on this candidate or recorded as Fail.",
      "Record whether people with disabilities evaluated the experience; if not, record the limitation.",
    ],
  },
  {
    id: "D1",
    group: "D",
    title: "Portuguese copy",
    criterion: "Every visitor-facing string is correct, calm, brief Brazilian Portuguese in Travessia's voice.",
    method: "Read every surface of both presentations and the page metadata against `content/editorial.ts`.",
    evidence: "A signed copy review listing every surface read.",
    threshold: "No spelling, accent, or punctuation error, mojibake, truncated text, placeholder copy, or mislabelled action; the tone is nature-led, never academic.",
    waivable: false,
    checks: [],
    captures: [{ id: "copy-review", label: "Portuguese copy review" }],
    checklist: [
      "Stop Cards, Stop Accounts, “Capítulos”, the closing card, and the itinerary.",
      "The editorial page, including the disclosure, credits, route entries, and footer.",
      "Failure lines, live-region messages, screen-reader-only text, alt text, and captions.",
      "The page title, description, and social image alt text.",
    ],
  },
  {
    id: "D2",
    group: "D",
    title: "Evidence Boundary",
    criterion: "Places, geography, marine life, seasons, and natural phenomena are real and plausible; Travessia, the Maré Mansa, its crew, and the itinerary are openly fictional and disclosed once per presentation.",
    method: "Check each Stop's claims (species, best season, landscape) against reputable public sources and review every surface for implied real-world operation.",
    evidence: "A signed Evidence Boundary review with the sources consulted.",
    threshold: "No invented wildlife or place, no implausible season, and nothing implying a real operator, booking, availability, price, or testimonial; no citation machinery.",
    waivable: false,
    checks: [],
    captures: [{ id: "boundary-review", label: "Evidence Boundary review" }],
    checklist: [
      "Each Stop's species, landscape, and best season are real and plausible.",
      "The fictional-project disclosure appears once in the 3D presentation (itinerary Sheet) and once on the editorial page.",
      "“Próxima partida · setembro de 2027” and the itinerary read as part of the fiction; there is no booking, lead form, or price.",
      "No testimonial, crew quote, or claim is presented as real.",
    ],
  },
  {
    id: "D3",
    group: "D",
    title: "Provenance and licences",
    criterion: "Every third-party or generated asset shipped has demonstrable rights, retained proof, and the attribution its licence requires.",
    method: "Review `content/asset-manifest.json`, `docs/third-party/`, and the rendered credits in both presentations.",
    evidence: "A signed provenance review.",
    threshold: "The AI-generated images, open geodata (OpenStreetMap ODbL and SRTM), the Ship model (CC BY), fonts (OFL), and dependency notices are recorded, and every required credit is visible where the asset appears.",
    waivable: false,
    checks: [],
    captures: [{ id: "provenance-review", label: "Provenance and licence review" }],
    checklist: [
      "The ledger's sources, rights, and proofs are complete for every shipped file.",
      "The OpenStreetMap and SRTM credit and the Ship credit are visible in both presentations.",
      "The AI-generated images are recorded in `docs/third-party/ai-generated-images.md`.",
      "Font licences and dependency notices match the shipped fonts and `bun.lock`.",
    ],
  },
  {
    id: "E1",
    group: "E",
    title: "Full Voyage on every device",
    criterion: "Every device in the mandatory suite completes the Voyage from Stop 00 to the Arrival in the 3D presentation.",
    method: "On each device: load cold, travel by scroll, touch, or keyboard, let the Ship settle, open every Stop Card and Stop Account, jump with “Capítulos”, restart, use sound, switch presentations, enable reduced motion, and rotate phones.",
    evidence: "A checklist and recording per device, with the device model, OS and browser versions, viewport, orientation, and power mode.",
    threshold: "Every device completes without an unintended fallback, context loss, crash, or outside help, and passes presentation continuity. An unavailable device is Unvalidated and blocks release until the supported suite is explicitly revised.",
    waivable: false,
    checks: [],
    captures: deviceSuite,
    checklist: [
      "Record the device model, OS and browser versions, viewport, orientation, power mode, and network.",
      "Travel Stop 00 → Arrival with the device's primary input; open every Stop Account; jump with “Capítulos”; restart.",
      "Switch to “Modo leitura” and back; reload; confirm the place and Visited Stops hold.",
      "Repeat a passage with reduced motion on; on phones, rotate during the Voyage.",
    ],
  },
  {
    id: "E2",
    group: "E",
    title: "Sustained frame budgets",
    criterion: "Physical rendering meets the approved sustained budgets through at least five active minutes.",
    method: "Enable the local diagnostic export (docs/production-assets.md), sail for at least five active minutes, and attach the exported JSON; the dossier checks that it names this candidate.",
    evidence: "The diagnostic export per device with p90 windows, tiers, and tier changes.",
    threshold: "Laptops sustain Balanced with p90 ≤20 ms and phones Low with p90 ≤33.3 ms after warm-up; no device changes tier more than twice after the first minute.",
    waivable: false,
    checks: [],
    captures: deviceSuite,
    checklist: [
      "`sessionStorage.setItem(\"ocean-drive:diagnostics\", \"enabled\")`, reload, then sail for at least five active minutes.",
      "Export with `copy(window.__oceanDiagnostics.exportJSON())` and save it as the evidence file.",
      "Record the initial and final tier, p50/p90, and every tier change after the first minute.",
    ],
  },
  {
    id: "E3",
    group: "E",
    title: "Timely 3D readiness",
    criterion: "The 3D voyage becomes ready quickly on real devices without ever blocking the page.",
    method: "Cold-load under a recorded production-like network and read the readiness milestone from the diagnostic export.",
    evidence: "The network profile and readiness timestamps per device.",
    threshold: "The Stop 00 card appears (readiness) within 8 seconds of navigation on every device.",
    waivable: false,
    checks: [],
    captures: deviceSuite,
    checklist: [
      "Clear site data, record the network (for example Wi-Fi or 4G, measured throughput), and load the page.",
      "Read the `readiness: ready` event time from the diagnostic export.",
    ],
  },
  {
    id: "E4",
    group: "E",
    title: "Thermal and motion comfort",
    criterion: "Motion and heat stay comfortable for the complete Voyage.",
    method: "The tester records motion comfort, heat, throttling, and stutter after warm-up and at the Arrival.",
    evidence: "A qualitative report plus any OS or browser performance evidence.",
    threshold: "No motion discomfort, no heat that makes a phone unpleasant to hold or visibly throttles the experience, and no sustained stutter. Any occurrence fails and requires a fix and a complete retest on that device.",
    waivable: false,
    checks: [],
    captures: deviceSuite,
    checklist: [
      "After five minutes: note heat, stutter, and any visible throttling.",
      "At the Arrival: note motion comfort and handling comfort.",
    ],
  },
  {
    id: "E5",
    group: "E",
    title: "Readability and controls on real screens",
    criterion: "The Ship, Landmarks, Stop Cards, Sheets, and chrome stay readable and operable on real screens and orientations.",
    method: "Inspect every Stop, both Sheets, the closing card, and the editorial page on each device, in both orientations on phones.",
    evidence: "Device photographs or captures and a checklist.",
    threshold: "No unreadable essential element, card covering its island or Ship, obscured control, browser-edge gesture conflict, or unreachable action.",
    waivable: false,
    checks: [],
    captures: deviceSuite,
    checklist: [
      "Each Stop Card stays clear of its Ship and Landmark and of the chrome.",
      "Swipes sail the Ship without triggering browser back, reload, or edge gestures.",
      "Sheets open on the correct side and close with one hand.",
    ],
  },
  {
    id: "E6",
    group: "E",
    title: "Failures reproduced and retested",
    criterion: "Every physical failure is reproduced, fixed, and retested on the affected device rather than averaged away.",
    method: "Keep a failure log with candidate, device, quality tier, steps, frequency, diagnostics, and the fix and retest link.",
    evidence: "The failure log.",
    threshold: "Every mandatory failure has a passing complete retest on the affected device and candidate; a pass on another device cannot clear it.",
    waivable: false,
    checks: [],
    captures: [{ id: "failure-log", label: "Physical failure log" }],
    checklist: ["List every failure from E1–E5 with its retest record on the new candidate, or state that none occurred."],
  },
  {
    id: "F1",
    group: "F",
    title: "First-time Visitors",
    criterion: "Three first-time Brazilian adults drawn to nature travel understand and complete the Voyage with no instruction beyond the scroll cue.",
    method: "Give each participant only the production interface on a supported device; observe one complete attempt, time it, then ask neutral teach-back questions about what Travessia is and what was real.",
    evidence: "A non-identifying profile, device, duration, assistance log, Stops opened, observed blockers, and a teach-back paraphrase per participant; a study summary.",
    threshold: "Every participant reaches the Arrival unaided, is never blocked by controls, readability, or unclear progression, and recognises that Travessia, its Ship, and its itinerary are fictional while the islands and wildlife are real; at least two of three finish in three to five minutes (study summary).",
    waivable: false,
    checks: [],
    captures: [
      { id: "participant-1", label: "Participant 1" },
      { id: "participant-2", label: "Participant 2" },
      { id: "participant-3", label: "Participant 3" },
      { id: "summary", label: "Study summary" },
    ],
    checklist: [
      "Recruit Brazilian adults drawn to nature travel with no prior exposure to the project; record only non-identifying details.",
      "Say only “Explore this site as you like”; offer no help unless asked, and log any help given.",
      "Time from first load to the Arrival; note Stops opened and any hesitation or blocker.",
      "Teach-back: “What is Travessia?” and “What in the voyage was real?”",
    ],
  },
  {
    id: "R1",
    group: "R",
    title: "Technical and accessibility sign-off",
    criterion: "A named technical and accessibility reviewer signs the automated, walkthrough, accessibility, and device sections for this candidate.",
    method: "Review rows A–C and E in the generated Release Dossier.",
    evidence: "A signed statement naming the candidate.",
    threshold: "Signed for this candidate after every reviewed row is recorded. If one person holds more than one role, the record states that independent review was unavailable.",
    waivable: false,
    checks: [],
    captures: [{ id: "technical", label: "Technical and accessibility reviewer" }],
    checklist: ["Sign only after every row in groups A, B, C, and E has a recorded result for this candidate."],
  },
  {
    id: "R2",
    group: "R",
    title: "Editorial sign-off",
    criterion: "A named editorial reviewer signs the copy, Evidence Boundary, provenance, and Visitor study sections for this candidate.",
    method: "Review rows D and F in the generated Release Dossier.",
    evidence: "A signed statement naming the candidate.",
    threshold: "Signed for this candidate after every reviewed row is recorded. If one person holds more than one role, the record states that independent review was unavailable.",
    waivable: false,
    checks: [],
    captures: [{ id: "editorial", label: "Editorial reviewer" }],
    checklist: ["Sign only after every row in groups D and F has a recorded result for this candidate."],
  },
  {
    id: "R3",
    group: "R",
    title: "Project-owner release verdict",
    criterion: "The project owner records the final release verdict for this candidate.",
    method: "Review the complete Release Dossier, including waivers and unvalidated risks.",
    evidence: "The owner's signed verdict naming the candidate.",
    threshold: "Pass records a release approval. The dossier still reports Blocked while any other row is not Pass or waived.",
    waivable: false,
    checks: [],
    captures: [{ id: "owner", label: "Project owner" }],
    checklist: ["Approve only when the generated dossier shows every other row as Pass or as a waived cosmetic Fail."],
  },
];
